# Generated by Django 2.2 on 2020-08-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_1_App', '0004_auto_20200822_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
