# Generated by Django 2.2 on 2020-08-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_1_App', '0006_auto_20200824_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
