# Generated by Django 2.2 on 2020-08-25 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project_1_App', '0007_auto_20200826_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='is_spam',
        ),
        migrations.AddField(
            model_name='message',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
