# Generated by Django 2.2 on 2020-09-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_1_App', '0008_auto_20200826_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='message_image'),
        ),
    ]
