# Generated by Django 2.2 on 2020-09-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project_1_App', '0014_auto_20200912_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
