# Generated by Django 2.2 on 2020-07-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_1_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
